name: Playwright Tests  # nome do nosso teste
on:  # trigger que vai definir quando vai ser executado
  push:
    branches: [ main, master ]  # 1ª Condição quando tivermos um push na branch main e master
  pull_request:
    branches: [ main, master ]
jobs:  # Tarefas a ser executada
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest  # Nessa etapa que o workflow define quem vai rodar os testes - basicamente uma máquina virtual
    steps:  # Steps que serão executados
      - uses: actions/checkout@v4  # Uses - sempre tá ativando um plugin no github action
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install  # Run -> Execuções das dependências para funcionar no ambiente ubuntu
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30  # Ele vai reter os relatórios por 30 dias

